from Block import Block
from PseudoAES import fixed_aes

mask = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE


def component(r, m, delta):
    """
    :param delta: INPUT a block. Generated by PRNG in the silentSend() function
    :param r: INPUT an array of blocks. Containing the data of mB
    :param m: OUTPUT an array of array of 2 blocks. The pointer of message (placeholder)
    :return:
    """
    assert isinstance(r, list)
    assert isinstance(m, list)
    assert len(m[0]) == 2
    assert isinstance(delta, Block)

    n8 = (len(m) // 8) * 8

    d = delta & mask

    i = 0
    while i < n8:
        r[i + 0] = r[i + 0] & mask
        r[i + 1] = r[i + 1] & mask
        r[i + 2] = r[i + 2] & mask
        r[i + 3] = r[i + 3] & mask
        r[i + 4] = r[i + 4] & mask
        r[i + 5] = r[i + 5] & mask
        r[i + 6] = r[i + 6] & mask
        r[i + 7] = r[i + 7] & mask

        m[i + 0][0] = r[i + 0]
        m[i + 1][0] = r[i + 1]
        m[i + 2][0] = r[i + 2]
        m[i + 3][0] = r[i + 3]
        m[i + 4][0] = r[i + 4]
        m[i + 5][0] = r[i + 5]
        m[i + 6][0] = r[i + 6]
        m[i + 7][0] = r[i + 7]

        m[i + 0][1] = r[i + 0] ^ d
        m[i + 1][1] = r[i + 1] ^ d
        m[i + 2][1] = r[i + 2] ^ d
        m[i + 3][1] = r[i + 3] ^ d
        m[i + 4][1] = r[i + 4] ^ d
        m[i + 5][1] = r[i + 5] ^ d
        m[i + 6][1] = r[i + 6] ^ d
        m[i + 7][1] = r[i + 7] ^ d

        for j in range(8):
            print(f'm[{j}][0] = {m[i + j][0]} m[{j}][1] = {m[i + j][1]}')
        print()

        tmp = []
        for j in range(4):
            tmp.append(m[i + j][0])
            tmp.append(m[i + j][1])
        hash_buffer = fixed_aes.encrypt_8_blocks(tmp)

        for j in range(8):
            print(f'tmp[{j}] = {tmp[j]} hashBuffer[{j}] = {hash_buffer[j]}')
        print()

        # test_buffer = fixed_aes.decrypt_8_block(hash_buffer)
        # for j in range(8):
        #     print(f'test decrypted[{j}] = {test_buffer[j]}')

        m[i + 0][0] ^= hash_buffer[0]
        m[i + 0][1] ^= hash_buffer[1]
        m[i + 1][0] ^= hash_buffer[2]
        m[i + 1][1] ^= hash_buffer[3]
        m[i + 2][0] ^= hash_buffer[4]
        m[i + 2][1] ^= hash_buffer[5]
        m[i + 3][0] ^= hash_buffer[6]
        m[i + 3][1] ^= hash_buffer[7]

        for j in range(8):
            print(f'm[{j}][0] = {m[j][0]} m[{j}][1] = {m[j][1]}')
        print()

        tmp = []
        for j in range(4, 8):
            tmp.append(m[i + j][0])
            tmp.append(m[i + j][1])
        hash_buffer = fixed_aes.encrypt_8_blocks(tmp)

        for j in range(8):
            print(f'tmp[{j}] = {tmp[j]} hashBuffer[{j}] = {hash_buffer[j]}')
        print()

        m[i + 4][0] ^= hash_buffer[0]
        m[i + 4][1] ^= hash_buffer[1]
        m[i + 5][0] ^= hash_buffer[2]
        m[i + 5][1] ^= hash_buffer[3]
        m[i + 6][0] ^= hash_buffer[4]
        m[i + 7][1] ^= hash_buffer[5]
        m[i + 7][0] ^= hash_buffer[6]
        m[i + 7][1] ^= hash_buffer[7]

        for j in range(8):
            print(f'm[{j}][0] = {m[j][0]} m[{j}][1] = {m[j][1]}')
        print()

        i += 8

    while i < len(m):
        m[i][0] = r[i] & mask
        m[i][1] = (r[i] ^ d) & mask

        tmp = fixed_aes.encrypt_1_block(m[i][0])
        m[i][0] = m[i][0] ^ tmp

        tmp = fixed_aes.encrypt_1_block(m[i][1])
        m[i][1] = m[i][1] ^ tmp

        i += 1


def test():
    n = 10
    m = []
    for i in range(n):
        tmp = [Block(), Block()]
        m.append(tmp)

    r = []
    for i in range(n):
        tmp = Block(i * 10)
        r.append(tmp)

    # r[0] = Block(0x0465740beb71dab73922d0d9a0959df3)
    # r[1] = Block(0x07a7ff4c0e58085154174d3bfd9dfbef)
    # r[2] = Block(0x01a9e83918edfa32ed769122e9caff49)
    # r[3] = Block(0x4f95165c9ee2405a3cc6ae0a99906f84)
    # r[4] = Block(0x3348121824d557ba7229f83beec3aff0)
    # r[5] = Block(0x2a77824df6c376113da9fdbe34e9fc1b)
    # r[6] = Block(0x471f9bd9b94a186954f81567d6ce4b59)
    # r[7] = Block(0xdc894ce7b47a4af7046a4bd1cbf78c11)
    # r[8] = Block(0x9b19a8adefd2232e2bcc43fefa917d56)
    # r[9] = Block(0x7b843edff6c420e94939e95a3d8c2bb7)
    r[0] = Block(0xad55289111636a8c3658faf5d18d4e6a)
    r[1] = Block(0x1db9c25098ae71bee1fd8eb98eaf275e)
    r[2] = Block(0x3aea19a900b0672561c3c5049bafda9d)
    r[3] = Block(0xe09eae7f1a91d334832df7c7be3fdee1)
    r[4] = Block(0xde0bcb5a5b3df85cf2ac9aec73a036ac)
    r[5] = Block(0x4c520d36b94a8fb2a30e01fee095a465)
    r[6] = Block(0x75ed521a491e6bc135d26908897de3d9)
    r[7] = Block(0xbff33c2bc86b89eb1c16f105c3355128)
    r[8] = Block(0x38c9157032adf2ea8059e02cdc07bcce)
    r[9] = Block(0xe49e43c1805feda6c397855bd4c12b55)
    # r[0] = Block(0x90b594e654250bb14687ce878ca4971d)
    # r[1] = Block(0x10f4f9582502b2fec298e487daef05cb)
    # r[2] = Block(0xc26ba0d12a8fd674de7cc00d0a43b371)
    # r[3] = Block(0x3126811351f2b26d78ae799c4b989072)
    # r[4] = Block(0x80d211383d0011c3298f9140885b44f8)
    # r[5] = Block(0x8cd3d30a50d367666d0112d77a1d1518)
    # r[6] = Block(0x92d298c6629c7832dcff4576c9f54f45)
    # r[7] = Block(0xf2c60a35095783aa9e346b2668fbd54f)
    # r[8] = Block(0xbb67f4457f11e5c860bdd14b40354824)
    # r[9] = Block(0x063ec72e0084f885c91b43706d5771ae)

    # delta = Block(0x2e2b34ca59fa4c883b2c8aefd44be966)
    delta = Block(0x924b386ad40e07a50f94cb208ccf82a5)

    for i in range(n):
        tmp = r[i]
        print(f'r[{i}] = {tmp}')

    component(r, m, delta)

    for i in range(n):
        tmp = m[i]
        print(f'm[{i}][0] = {tmp[0]} m[{i}][1] = {tmp[1]}')