from PseudoAES import PseudoAES

aes = [PseudoAES(3242342), PseudoAES(8993849)]


def component(delta, seed, output):
    """
    :param delta: INPUT a block. Generated by PRNG in the silentSend() function
    :param seed: INPUT a block. Generated by PRNG as the seed of GGM tree
    :param output: OUTPUT a list of blocks. A sublist of mB vector (size = mSizePer * mNumPartitions)
    """
